### ISSUE TITLE
Generated configuration not taken in account

### ISSUE THREAD

**Issue by ptitjes** [SnowMB/nextcloud#12]
This is more of a question for now.

I borrowed your `generate-config` script, so I generate my `config.php` in this way and copy it to `/usr/src/nextcloud/config` correctly. By login into the container, I can see the correct generated information is rsync as a result in `/var/www/html` and with the right permissions. However, as you tell in your documentation, we still need to enter the same data during the configuration wizard.

Is there a way to avoid that ?

**Comment by SnowMB** [comment]
Yeah bothered me as well, but I didn't work on in any further, because most of the times I migrate instead of creating a new instance, so I don't use the script.

I think one way would be to alter the command on first run to perform a [command line installation](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/occ_command.html#command-line-installation-label).

**Comment by ptitjes** [comment]
Figured it :) I also generate an `autoconfig.php` file at build time, next to the `config.php` file, following what Wonderfall does (but at runtime).

I will close this issue.
