### ISSUE TITLE
No need to expose port

### ISSUE THREAD

**Issue by pierreozoux** [SnowMB/nextcloud#2]
You don't need to expose this port as this will be served by nginx+letsencrypt:

https://github.com/SnowMB/nextcloud/blob/master/collabora/docker-compose.yml#L87

**Comment by SnowMB** [comment]
Thanks will check into that.

Edit: I remember why I put that in. The examples publicly expose the port by binding it to a port on the host with "ports:" or the -p option. As I did't want the collabora container to be excessible without going through the proxy (I don't want the collabora port exposed on my host), I tried running the container without that option. Seems that their dockerfile didn't specify the exact port as exposed, so that it was not accessible. 

Beware that expose only gives the docker engine and other containers in the same docker network the possibillity to access the port.
