### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by elmero1** [SnowMB/nextcloud#8]
Hi i use your docker-compose file and updated nextcloud with the WebUpdater (maybe the problem). After the update and a restart i have the following message:
Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.2.2 to 9.1.1.5)

When i change the version in the config file to 10.0.2 the i have the following message:
Downgrading is not supported and is likely to cause unpredictable issues (from 10.0.2 to 9.1.1.5)

Thanks for your support.

**Comment by SnowMB** [comment]
Hey,
Nextcloud uses a diffrent version numbering scheme in the config file. Try using 9.1.2.2 instead.

**Comment by elmero1** [comment]
The same failure:
Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.2.2 to 9.1.1.5)

i think the problem was the web updater. The database and the files are only compatible with the new version (9.1.2.2 / 10.0.2), but the docker contrainer is still the old version 9.1.1.5 / 10.0.1.

**Comment by SnowMB** [comment]
Hey,

I tried to repoduce your error today, but for me updating with the new updater went smoothly without any problems. Can you provide some logs?

**Edit**: Nevermind, I just tried updating from 10.0.2 -> 11.0 which runs fine. Haven't seen that you struggle on 10.0.2. I will try to repoduce this as well. 

I just updated by destroying and recreating the docker-container. I would recommend updating that way, because if you somehow have to recreate the container after the upgrade and there is no new version in place you might face same problem.

**Comment by SnowMB** [comment]
Ok I just did an update 10.0.1 -> 10.0.2 with the update script. Works for me as well.
But like I said, the update will be lost if the docker-container is recreated. (Right now the container image still uses 10.0.1). 
Then you will run in the error you described. I can repoduce that. So your guess was right, problem is that config and database are on 10.0.2 and the container is on 10.0.1.

You have 2 options now:

- go to you config.php and change the version number to 9.1.1.5 then you will go back to 10.0.1 which worked for me in a quick test, but might be unstable (I don't know what changes were made to the databse and files from 10.0.1 -> 10.0.2)
- Get your docker-container image to 10.0.2
